import type { Metadata } from "next";
import { Geist, Geist_Mono, Homemade_Apple } from "next/font/google";
import "./globals.css";
import Navbars from "./component/Navbars/Navbars";
import Footer from "./component/Footer/Footer";
import Homee from "./Homee/Homee";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "stort app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbars />
        {children}
        <Footer />
      </body>
    </html>
  );
}
